/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Subtask {
  'id' : SubtaskId,
  'title' : string,
  'isCompleted' : boolean,
}
export type SubtaskId = bigint;
export interface Task {
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : string,
  'assignedTo' : [] | [Principal],
  'createdAt' : bigint,
  'createdBy' : Principal,
  'tags' : Array<string>,
  'dueDate' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'priority' : TaskPriority,
  'orderKey' : [] | [bigint],
  'subtasks' : Array<Subtask>,
}
export type TaskId = bigint;
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'urgent' : null } |
  { 'medium' : null };
export type TaskStatus = { 'open' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'archived' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSubtask' : ActorMethod<[TaskId, string], Subtask>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<
    [string, string, bigint, TaskPriority, Array<string>],
    Task
  >,
  'deleteSubtask' : ActorMethod<[TaskId, SubtaskId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedTaskCount' : ActorMethod<[], bigint>,
  'getTaskCount' : ActorMethod<[], bigint>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getTasksByStatus' : ActorMethod<[TaskStatus], Array<Task>>,
  'getTasksSortedByDueDate' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleSubtaskCompletion' : ActorMethod<[TaskId, SubtaskId], Subtask>,
  'updateSubtask' : ActorMethod<[TaskId, SubtaskId, string], Subtask>,
  'updateTask' : ActorMethod<
    [TaskId, string, string, bigint, TaskPriority, Array<string>],
    Task
  >,
  'updateTaskOrder' : ActorMethod<[TaskStatus, Array<TaskId>], undefined>,
  'updateTaskStatus' : ActorMethod<[TaskId, TaskStatus], Task>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];