/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskId = IDL.Nat;
export const SubtaskId = IDL.Nat;
export const Subtask = IDL.Record({
  'id' : SubtaskId,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
  'medium' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'archived' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'tags' : IDL.Vec(IDL.Text),
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'priority' : TaskPriority,
  'orderKey' : IDL.Opt(IDL.Nat),
  'subtasks' : IDL.Vec(Subtask),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSubtask' : IDL.Func([TaskId, IDL.Text], [Subtask], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, TaskPriority, IDL.Vec(IDL.Text)],
      [Task],
      [],
    ),
  'deleteSubtask' : IDL.Func([TaskId, SubtaskId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedTaskCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTaskCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksByStatus' : IDL.Func([TaskStatus], [IDL.Vec(Task)], ['query']),
  'getTasksSortedByDueDate' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleSubtaskCompletion' : IDL.Func([TaskId, SubtaskId], [Subtask], []),
  'updateSubtask' : IDL.Func([TaskId, SubtaskId, IDL.Text], [Subtask], []),
  'updateTask' : IDL.Func(
      [TaskId, IDL.Text, IDL.Text, IDL.Int, TaskPriority, IDL.Vec(IDL.Text)],
      [Task],
      [],
    ),
  'updateTaskOrder' : IDL.Func([TaskStatus, IDL.Vec(TaskId)], [], []),
  'updateTaskStatus' : IDL.Func([TaskId, TaskStatus], [Task], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskId = IDL.Nat;
  const SubtaskId = IDL.Nat;
  const Subtask = IDL.Record({
    'id' : SubtaskId,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'priority' : TaskPriority,
    'orderKey' : IDL.Opt(IDL.Nat),
    'subtasks' : IDL.Vec(Subtask),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSubtask' : IDL.Func([TaskId, IDL.Text], [Subtask], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, TaskPriority, IDL.Vec(IDL.Text)],
        [Task],
        [],
      ),
    'deleteSubtask' : IDL.Func([TaskId, SubtaskId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedTaskCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTaskCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksByStatus' : IDL.Func([TaskStatus], [IDL.Vec(Task)], ['query']),
    'getTasksSortedByDueDate' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleSubtaskCompletion' : IDL.Func([TaskId, SubtaskId], [Subtask], []),
    'updateSubtask' : IDL.Func([TaskId, SubtaskId, IDL.Text], [Subtask], []),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Text, IDL.Int, TaskPriority, IDL.Vec(IDL.Text)],
        [Task],
        [],
      ),
    'updateTaskOrder' : IDL.Func([TaskStatus, IDL.Vec(TaskId)], [], []),
    'updateTaskStatus' : IDL.Func([TaskId, TaskStatus], [Task], []),
  });
};

export const init = ({ IDL }) => { return []; };