/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Subtask {
    id: SubtaskId;
    title: string;
    isCompleted: boolean;
}
export type TaskId = bigint;
export type SubtaskId = bigint;
export interface Task {
    id: TaskId;
    status: TaskStatus;
    title: string;
    assignedTo?: Principal;
    createdAt: bigint;
    createdBy: Principal;
    tags: Array<string>;
    dueDate: bigint;
    description: string;
    updatedAt: bigint;
    priority: TaskPriority;
    orderKey?: bigint;
    subtasks: Array<Subtask>;
}
export interface UserProfile {
    name: string;
}
export enum TaskPriority {
    low = "low",
    high = "high",
    urgent = "urgent",
    medium = "medium"
}
export enum TaskStatus {
    open = "open",
    completed = "completed",
    inProgress = "inProgress",
    archived = "archived"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSubtask(taskId: TaskId, title: string): Promise<Subtask>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTask(title: string, description: string, dueDate: bigint, priority: TaskPriority, tags: Array<string>): Promise<Task>;
    deleteSubtask(taskId: TaskId, subtaskId: SubtaskId): Promise<void>;
    deleteTask(taskId: TaskId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompletedTaskCount(): Promise<bigint>;
    getTaskCount(): Promise<bigint>;
    getTasks(): Promise<Array<Task>>;
    getTasksByStatus(status: TaskStatus): Promise<Array<Task>>;
    getTasksSortedByDueDate(): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleSubtaskCompletion(taskId: TaskId, subtaskId: SubtaskId): Promise<Subtask>;
    updateSubtask(taskId: TaskId, subtaskId: SubtaskId, title: string): Promise<Subtask>;
    updateTask(taskId: TaskId, title: string, description: string, dueDate: bigint, priority: TaskPriority, tags: Array<string>): Promise<Task>;
    updateTaskOrder(status: TaskStatus, orderedTaskIds: Array<TaskId>): Promise<void>;
    updateTaskStatus(taskId: TaskId, newStatus: TaskStatus): Promise<Task>;
}
import type { Subtask as _Subtask, Task as _Task, TaskId as _TaskId, TaskPriority as _TaskPriority, TaskStatus as _TaskStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSubtask(arg0: TaskId, arg1: string): Promise<Subtask> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubtask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubtask(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: bigint, arg3: TaskPriority, arg4: Array<string>): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_TaskPriority_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Task_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_TaskPriority_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Task_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSubtask(arg0: TaskId, arg1: SubtaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubtask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubtask(arg0, arg1);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedTaskCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedTaskCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedTaskCount();
            return result;
        }
    }
    async getTaskCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskCount();
            return result;
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByStatus(arg0: TaskStatus): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByStatus(to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByStatus(to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksSortedByDueDate(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksSortedByDueDate();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksSortedByDueDate();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleSubtaskCompletion(arg0: TaskId, arg1: SubtaskId): Promise<Subtask> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSubtaskCompletion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSubtaskCompletion(arg0, arg1);
            return result;
        }
    }
    async updateSubtask(arg0: TaskId, arg1: SubtaskId, arg2: string): Promise<Subtask> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubtask(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubtask(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: string, arg2: string, arg3: bigint, arg4: TaskPriority, arg5: Array<string>): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_TaskPriority_n3(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Task_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_TaskPriority_n3(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Task_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTaskOrder(arg0: TaskStatus, arg1: Array<TaskId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskOrder(to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskOrder(to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async updateTaskStatus(arg0: TaskId, arg1: TaskStatus): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Task_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Task_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_TaskPriority_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: _TaskStatus;
    title: string;
    assignedTo: [] | [Principal];
    createdAt: bigint;
    createdBy: Principal;
    tags: Array<string>;
    dueDate: bigint;
    description: string;
    updatedAt: bigint;
    priority: _TaskPriority;
    orderKey: [] | [bigint];
    subtasks: Array<_Subtask>;
}): {
    id: TaskId;
    status: TaskStatus;
    title: string;
    assignedTo?: Principal;
    createdAt: bigint;
    createdBy: Principal;
    tags: Array<string>;
    dueDate: bigint;
    description: string;
    updatedAt: bigint;
    priority: TaskPriority;
    orderKey?: bigint;
    subtasks: Array<Subtask>;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n7(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedTo: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.assignedTo)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        tags: value.tags,
        dueDate: value.dueDate,
        description: value.description,
        updatedAt: value.updatedAt,
        priority: from_candid_TaskPriority_n10(_uploadFile, _downloadFile, value.priority),
        orderKey: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.orderKey)),
        subtasks: value.subtasks
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    urgent: null;
} | {
    medium: null;
}): TaskPriority {
    return "low" in value ? TaskPriority.low : "high" in value ? TaskPriority.high : "urgent" in value ? TaskPriority.urgent : "medium" in value ? TaskPriority.medium : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    open: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    archived: null;
}): TaskStatus {
    return "open" in value ? TaskStatus.open : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : "archived" in value ? TaskStatus.archived : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n5(_uploadFile, _downloadFile, x));
}
function to_candid_TaskPriority_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    open: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    archived: null;
} {
    return value == TaskStatus.open ? {
        open: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value == TaskStatus.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    low: null;
} | {
    high: null;
} | {
    urgent: null;
} | {
    medium: null;
} {
    return value == TaskPriority.low ? {
        low: null
    } : value == TaskPriority.high ? {
        high: null
    } : value == TaskPriority.urgent ? {
        urgent: null
    } : value == TaskPriority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
